### PR TITLE
Add possibility to customise colours of the icons

### PR DESCRIPTION
**Pull request by giabaio**
Hi there - I have made a minor tweak to the `lua` file, so that colours can be customised when printing the icons. Would you be interested in merging this?

### CODE REVIEW

**Comment by cscheid** [comment]
Thanks for the contribution and interest. The idea is sound. I just wonder if the right way to do it is a little more careful (if someone else wants to add another style, then we'll have repeating `style` tags). Are you interested in building out a proper fix for this? We'll need a contributor agreement from you as well https://quarto.org/about.html#contribute

**Comment by giabaio** [comment]
Thanks. I guess this makes sense - I am not sure whether I've reached the limit of my `lua` expertise, though --- I was simply adding very simple code to the existing one to update it for my specific needs. Understood that others may want to increase the customisation, though...

**Comment by cscheid** [comment]
If you have a simple color need, it's possible that you can address it without changing the extension at all, instead simply wrapping the FA invocations in a div with a custom class, and then using CSS.

**Comment by mcanouil** [comment]
If I may, the easiest way to add colour or whatever styling would be to use spans, *e.g.*,
```
[{{< fa chess-pawn >}}]{style="color: #b22222;"}
```

In addition, style should be the variable, not colour if such feature would come to this extension in my opinion.

**Comment by cscheid** [comment]
I generally agree, and I think @mcanouil's solution with spans is good enough that we don't need a feature like this on the extension itself.

**Pull request closed without merging**
