### PR TITLE
Update to 6.5.2

### PR DESCRIPTION
**Pull request by bethanyhgardner**
I needed the Upwork and Bluesky icons that were added in v6.5, so I modified the asset files in my project's installation of the extension, modeling it after the changes in #32. Here it is, in case anyone else needs it! It works for my website, adding both new icons and icons that have existed in previous versions, but I'm not sure if there's a conventional way to test the full set of icons and the various ways to insert them.

### CODE REVIEW

**Comment by cscheid** [comment]
Thanks, @bethanyhgardner, this looks great.

A few questions:

- For larger PRs like this, we need you to file a contributor agreement with Posit. Can you follow the instructions on https://github.com/quarto-dev/quarto-cli/blob/main/CONTRIBUTING.md (specifically bullet point 2) and confirm on a reply here that you've done so?

- Is the .css file a copy of the new font-awesome release? The only reason I ask is that some of the font names changed from "free" back to the other files that we're still shipping, but haven't changed. I worry a little that we're doing the wrong thing here. We'd love to merge this, but I just want to understand a bit better what's happening in those declarations.

**Comment by bethanyhgardner** [comment]
Hi,

Ahh, sorry for my delayed response! I just submitted the contributor agreement.

I downloaded the free web version of fontawesome 6.5.2 and cross-referenced the files there with the ones included in this extension (the .ttf and .woff2 files in `webfonts/` and `all.css` in `css/`). Looking at the [font awesome release notes](https://fontawesome.com/changelog), I'm not sure if the update makes changes to file naming structure that would affect this extension, beyond just adding additional icons.

**Comment by lnnrtwttkhn** [comment]
Would be lovely to have this merged! Thanks @bethanyhgardner for the PR!

**Comment by robjhyndman** [comment]
What's holding this PR up? It would be great to have fontawesome updated to the latest version. (I know I can just install the version from @bethanyhgardner.)

**Review by cderv — APPROVED** [review]
Sorry for the delay on this one. 

> I downloaded the free web version of fontawesome 6.5.2 and cross-referenced the files there with the ones included in this extension (the .ttf and .woff2 files in webfonts/ and all.css in css/).

I think this is the right way to do it. The change we see is because the previous update 6.4.2 was not exactly using the all.css for the 6.4.2 free download of fontawesome release. 

This PR makes things cleaner for future update regarding this extension providing equivalent of Free release of fontawesome at https://github.com/FortAwesome/Font-Awesome/releases

> the other files that we're still shipping, but haven't changed.

I think we need to remove those.

**Pull request merged**
