### PR TITLE
Accessiblity

### PR DESCRIPTION
**Pull request by mcanouil**
This PR does:

- Improve accessibility (#8):
  - Adds `aria-label` attribute.

### CODE REVIEW

**Comment by cscheid** [comment]
Let's not do the license change on this one, because if we do that, we want to synchronize that change along all extensions in `quarto-ext`. Can you revert that part, please?

**Comment by cscheid** [comment]
(I somehow was missing some notifications on this repo. Sorry about the delay. This looks good.)

**Comment by mcanouil** [comment]
I was hoping for someone to confirm screen reader was working before merging, thus draft, although the changes can not hurt anyway.

I tried the MacOS screen reader on different syntax, but it does not seem to work or I am mistaken about how it's suppose to work, so I stayed to the current one in that branch based on several accessibility recommendations.

**Comment by cscheid** [comment]
Ok, thanks for the added context.

**Pull request merged**
