### PR TITLE
FontAwesome 6.4.2 Update

### LINKED ISSUE #28: Any plans to support the new Twitter/X Logo?
Hi folks!

As far as I can see the current fontawesome(-extention) can't display the new X Logo (formerly know as twitter). Does someone have a work around or will there be an update soon?

Yours
Norman

### LINKED ISSUE #29: Update fontawesome embed version
This will also solve

- [x] #28

### PR DESCRIPTION
**Pull request by philkleer**
Dear all, 

I saw that the issue and task for implementing 6.4.2 is still open (https://github.com/quarto-ext/fontawesome/issues/28). Since I needed 6.4.2 support for my presentation (new twitter logo), I updated the .css-files to 6.4.2 and the ttf/woff2 files. In case this might help you or is interesting to you, use it!

All the best
Phil

### CODE REVIEW

**Comment by cscheid** [comment]
Hey Phil, this looks excellent, thank you so much! I think that for larger PRs like this, we need you to file a contributor agreement with Posit. Can you follow the instructions on https://github.com/quarto-dev/quarto-cli/blob/main/CONTRIBUTING.md and confirm on a reply here that you've done so?

**Comment by philkleer** [comment]
Hey Carlos, 

please find attached the document (I put the email-address from contributing in CC). So, I need to re-do the pull request according to contributin.md, right?

All the best
Phil

￼

**Comment by cscheid** [comment]
No, no need to redo the pull request!

**Comment by cscheid** [comment]
LGTM, thanks for the contribution!

**Comment by philkleer** [comment]
You’re welcome. I heavily use it. Thanks for providing and maintaining it!

**Pull request merged**
